# /////////////////////////////////////////////////////////////////  PAGE SETTINGS
baseurl = "https://orangecirclecompany.com/"
title = "Orange Circle Company"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  custom_css = ["css/custom.css"]
  favicon = "favicon.ico"
  author = "orange circle company"
  description = "Website, SEO and Copywriting Services"
  email = "info@orangecirclecompany.com"
  icon = "icon-home"

  [taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[prmalinks]
  services = "/title"
  #//////////////////////////////////////////////////////////////////   NAVIGATION
  [params.navigation]
    brand = "OCC"
    home = "Home"
    testimonials = "Testimonials"
    services = "Services"
    process = "Process"
    work = "Work"
    about = "About"
    portfolio = "Portfolio"
    contact = "Contact"

  # //////////////////////////////////////////////////////////////////  HERO SECTION
  [params.hero]
    title = 'Orange Circle Company'
    brand = 'The <mark>Everywhere</mark> Agency'
    subtitle = 'Website - SEO - Copywriting'
  # ///////////////////////////////////////////////////////////////////  INTRO SECTION
  [params.intro]
    enable = true
    [[params.intro.item]]
    title = "Successful Digital Solutions"
    description = "We are experts in the field of producing high quality digital solutions. After working over 7 years in the field, we have decided to share that expertise with you. We produce high quality websites and digital marketing solutions."
    url = "#contact"
    button = "Get In Touch"
    icon = "icon-bulb"
    # img = "images/team/boo.jpg"
    [[params.intro.item]]
    title = "Reach New Customers"
    description = "Online marketing is not only fun, but its also extremely rewarding. People wouldn't spend money on online marketing if it didn't work. We would like to show your business that it too can benefit from online marketing, and see results quickly."
    url = "#contact"
    button = "How?"
    icon = "icon-wrench"
    img = ""
    [[params.intro.item]]
    title = "Launch your business to new heights"
    description = "We will launch and maintain your site or marketing campaign. We provide detailed digital reports that update in real time, always accessible for our clients. See where every dollar goes, where every potential lead comes from, see your new website take sail."
    url = "#contact"
    button = "Why us?"
    icon = "icon-rocket"
    img = ""
    [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"

  # ///////////////////////////////////////////////////////////////  PROCESS SECTION
  [params.process]
    enable = false
    title = "Our Process"
    description = "How we do what we do"
  # //////////////////////////////////////////////////////////////  SERVICES SECTION
  [params.services]
    enable = true
    title = "Services"
    description = "What We Can Do For You"
      [[params.services.item]]
        title = "Coding"
        url = "services/coding/"
        description = "Have an idea for a website or an app? We at Orange Circle Company want to help your ideas become reality. We produce websites, webapps, and mobile apps that work across all devices."
        icon = "icon-headphones"
      [[params.services.item]]
        title = "Websites"
        url = "services/websites"
        description = "A good website can provide your potential customers with everything they need to know and help them feel comfortable when choosing your business. We have a number of website solutions to fit any kind of business."
        icon = "icon-compass"
      [[params.services.item]]
        title = "SEO"
        url = "services/seo"
        description = "Show up on the first page of Google! Ever wonder how many people visit your website? With our analytics services we can provide detailed interactive reports that explain in detail who is visiting your website and from where."
        icon = "icon-pie-chart"
      [[params.services.item]]
        title = "Copywriting"
        url = "services/copywriting"
        description = "Copy-writing is the most basic and important part of any project. riting good copy is something we take very seriously. All the copy we write for our clients is both pleasing to read and SEO rich."
        icon = "icon-pencil"
      [[params.services.item]]
        title = "Google Ads"
        url = "services/google-ads"
        description = "Google Ads are a fantastic way to spread awareness of your business online. It is important to have both a SEO strategy and a Google Ads strategy that work well together. We at Orange Circle Company can make that happen."
        icon = "icon-google"
        [[params.services.item]]
        title = "Multimedia"
        url = "services/multimedia"
        description = "Optimized multimedia content on your website is essential.  We can optimize your image, video and graphic content for top performance"
        icon = "icon-picture"

  # /////////////////////////////////////////////////////////////////  WORK SECTION
  [params.work]
    enable = false
    title = "Work"
    description = "Some of Our Projects"
    footertext = ''
    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Asla Land"
      subtitle = "A Custom Blog"
      url = "#/"
    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Cast of Crowns"
      subtitle = "WordPress SEO  &amp  Optimizations"
    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image3"
      title = "Ficcadenti Waggoner &amp Castle"
      subtitle = "WordPress  &amp  CSS Frontend"
      url = "#/"
    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "The Special Olympics"
      subtitle = "Artwork &amp Frontend"
      url = "#/"
    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Abbot Technologies"
      subtitle = "Design"
      url = "#/"
    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"
      url = "#/"
  # /////////////////////////////////////////////////////////////////  TESTIMONIALS SECTION
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"
    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"
    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
  # //////////////////////////////////////////////////////////////////////////////  ABOUT SECTION
  [params.about]
    enable = true
    title = "Our Team"
    description = "We Make It Happen"
    [[params.about.item]]
      name = "Bia"
      position = "Web Developer & Analytics"
      description = "Enjoys her cats. Hobbies include gardening, web development, cooking"
      img = "loki.jpg"
      alt = "Loki"
      social = [
        ["icon-globe", "https://biamccrory.com"],
        ["icon-github", "https://github.com/biamccrory"]
      ]
    [[params.about.item]]
      name = "Arron"
      position = "Web Developer & CEO"
      description = "Enjoys being creative & traveling. Hobbies include playing video games, making websites, making music"
      img = "arron.jpg"
      alt = "Arron"
      social = [
        ["icon-globe", "https://arronmccrory.com"],
        ["icon-github", "https://github.com/arron21"]
      ]
    [[params.about.item]]
      name = "Justine"
      position = "Copywriter"
      description = "Enjoys a good screenplay & theatre. Hobbies include teaching drama and running"
      img = "justine.jpg"
      alt = "Justine"
      social = [
        ["icon-globe", "https://justinerea.com"],
      ]

  # /////////////////////////////////////////////////////////////////////////////  COUNTERS SECTION
  [params.counters]
    enable = false
    title = "Stats"
    # background = "full_image_1.jpg"
    url = "http://www.internetlivestats.com/watch/websites/"
    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000
    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000
    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000
    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000
      [params.counter.video]
        enable = true
        title = "Stats"
        url = "http://www.internetlivestats.com/watch/websites/"
  # /////////////////////////////////////////////////////////////////////  CONTACT SECTION
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = " Give us a call! "
    details = [
        ["icon-home", "The City of Orange, but really we are everywhere"],
        ["icon-phone", "(949) 329-5030"],
        ["icon-envelope", "info@orangecirclecompany.com"],
      ]
    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send"
  # ///////////////////////////////////////////////////////////////////////////  FOOTER SECTION
  [params.footer]
    enable = true
    copyright = '&copy; Orange Circle Company 2018 All Rights Reserved'
    links = [
        # ["icon-twitter", "#twitter"],
        # ["icon-facebook", "#facebook"],
        # ["icon-youtube", "#youtube"]
      ]
